# Site
name: "Baseball Chat"
title: "Baseball Chatbot"
description: "We can answer your questions about baseball"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://baseballChatbot7.github.io"
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: mj.jo.sw@gmail.com

# Authors
authors:
  happyBeagle:
    name: Minjung
    display_name: happyBeagle
    gravatar: fac2239fb739a49a376a874dde21dd71
    email: mj.jo.sw@gmail.com
    web: https://happybeagle.github.io/
    description: "backend, ml, dl, hardware"
  skaurl:
    name: NamHyeok Kim
    display_name: skaurl
    gravatar: 202e850e5f0b9603223ba94cc692d7d1
    email: dr_lunars@naver.com
    web: https://velog.io/@skaurl
    description: "nlp, statistics"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
